import './isolate.mjs';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { request } from 'node:http';
import { fileURLToPath } from 'node:url';
import { createWebServer } from '../web/server.mjs';
const here = dirname(fileURLToPath(import.meta.url));
const root = await mkdtemp(join(tmpdir(), 'pi-web-test-'));
const options = { dataDir: join(root, 'data'), workspace: root, piBin: process.execPath, piArgs: [join(here, 'fixtures/pi-rpc.mjs')], env: { ...process.env, HOME: root, FAKE_RPC_LOG: join(root, 'rpc.log') }, publicOrigin: 'https://pi.example.ts.net', tailscaleUser: 'owner@example.com' };
let app, base, origin, events;
async function launch() { app = await createWebServer(options); await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve)); base = origin = `http://127.0.0.1:${app.server.address().port}`; }
async function call(path, body, headers = {}) {
  return new Promise((resolve, reject) => {
    const req = request(path.startsWith('/') ? `${base}${path}` : `${base}/api/${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { ...(body === undefined ? {} : { Origin: origin, 'Content-Type': 'application/json', 'X-Pi-Web': '1' }), ...headers } }, res => {
      let text = ''; res.setEncoding('utf8'); res.on('data', chunk => text += chunk); res.on('end', () => { try { resolve({ status: res.statusCode, data: res.headers['content-type']?.includes('application/json') ? JSON.parse(text) : text }); } catch (e) { reject(e); } });
    }); req.on('error', reject); req.end(body === undefined ? undefined : JSON.stringify(body));
  });
}
async function until(predicate) { for (let i = 0; i < 100; i++) { const state = (await call('state')).data; if (predicate(state)) return state; await new Promise(resolve => setTimeout(resolve, 15)); } throw Error('Timed out waiting for state'); }
try {
  await assert.rejects(createWebServer({ ...options, tailscaleUser: '' }), /PI_WEB_TAILSCALE_USER/);
  await launch();
  assert.equal((await call('state')).data.online, false, 'Page loading must not start a model request');
  assert.equal((await call('health', undefined, { Host: 'evil.test' })).status, 403);
  assert.equal((await call('health', undefined, { 'X-Forwarded-For': '100.64.0.2', 'Tailscale-User-Login': 'other@example.com' })).status, 403, 'Proxy request cannot forge localhost Host to bypass owner authorization');
  assert.equal((await call('health', undefined, { 'X-Forwarded-For': '100.64.0.2' })).status, 403, 'Tagged devices without owner identity cannot use localhost bypass');
  assert.equal((await call('sessions', {}, { Origin: 'https://evil.test' })).status, 403);
  assert.equal((await call('sessions', {}, { 'X-Pi-Web': '' })).status, 415);
  assert.equal((await call('health', undefined, { Host: 'pi.example.ts.net' })).status, 403);
  assert.equal((await call('health', undefined, { Host: 'pi.example.ts.net', 'Tailscale-User-Login': 'other@example.com' })).status, 403);
  assert.equal((await call('health', undefined, { Host: 'pi.example.ts.net', 'Tailscale-User-Login': 'owner@example.com' })).status, 200);
  const navigationHeaders = { Host: 'pi.example.ts.net', 'Tailscale-User-Login': 'owner@example.com', 'X-Forwarded-For': '100.64.0.2', 'Sec-Fetch-Site': 'cross-site', 'Sec-Fetch-Mode': 'navigate', 'Sec-Fetch-Dest': 'document' };
  const navigation = await call('/', undefined, navigationHeaders);
  assert.equal(navigation.status, 200, 'An owner following a link from another site can open the app');
  assert.ok(navigation.data.includes('<title>Zen Pi'));
  assert.equal((await call('/', undefined, { ...navigationHeaders, 'Tailscale-User-Login': 'other@example.com' })).status, 403, 'Navigation still requires the Tailscale owner');
  assert.equal((await call('/', undefined, { ...navigationHeaders, Origin: 'https://evil.test' })).status, 403, 'Navigation cannot bypass mismatching Origin');
  assert.equal((await call('/app.js', undefined, { ...navigationHeaders, 'Sec-Fetch-Mode': 'no-cors', 'Sec-Fetch-Dest': 'script' })).status, 403, 'Cross-site subresource loading remains blocked');
  assert.equal((await call('state', undefined, { ...navigationHeaders, 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Dest': 'empty' })).status, 403, 'Cross-site API reads remain blocked');
  assert.equal((await call('sessions', {}, { ...navigationHeaders, Origin: '' })).status, 403, 'POST cannot use the document navigation exception');
  assert.equal((await call('sessions', {}, { Host: 'pi.example.ts.net', Origin: 'https://pi.example.ts.net', 'Tailscale-User-Login': 'owner@example.com' })).status, 200);
  let state = (await call('state')).data, id = state.sessionId;
  assert.equal(state.mode, 'general');
  assert.equal(state.notice, '', 'Internal /mode status JSON is already represented by structured controls');
  assert.ok(!JSON.stringify(state).includes('DO-NOT-EXPOSE'));
  assert.ok(!JSON.stringify(state).includes('SECRET'));
  assert.ok(state.workspaces.some(workspace => workspace.path === root), 'Workspace paths are intentionally shown to their owner');
  assert.ok(!JSON.stringify(state).includes(join(root, 'data', 'sessions')), 'Internal session file paths remain private');
  assert.ok(state.sessions.every(session => !('file' in session)));
  await call('prompt', { sessionId: id, message: '/test-feedback' });
  state = (await call('state')).data;
  assert.equal(state.notice, JSON.stringify({ warning: '需要保留的提醒' }), 'Unrelated JSON notifications remain visible');
  assert.equal(state.error, '筆記庫暫時無法讀取。', 'Actual errors remain visible');
  const study = await call('mode', { sessionId: id, mode: 'study' });
  assert.equal(study.status, 200); assert.equal(study.data.mode, 'study');
  assert.equal(study.data.notice, '', 'Study cannot show stale general mode JSON or previous notifications');
  assert.equal(study.data.error, '', 'A successful mode operation clears the previous error');
  assert.equal((await call('notes', { sessionId: id, query: 'Network' })).data.notes[0].title, 'Network');
  assert.equal((await call('note', { sessionId: id, path: '/etc/passwd' })).status, 400);
  await call('prompt', { sessionId: id, message: '/test-feedback' });
  state = (await call('note', { sessionId: id, path: '03-Network/Network.md' })).data;
  assert.equal(state.context.current, '03-Network/Network.md');
  assert.equal(state.notice, '', 'A successful note choice clears prior notifications');
  assert.equal(state.error, '', 'A successful note choice clears the prior error');
  assert.equal(state.sources.length, 0);
  const firstId = id;
  state = (await call('sessions', {})).data;
  assert.notEqual(state.sessionId, firstId);
  assert.equal(state.mode, 'general');
  state = (await call('open', { id: firstId })).data;
  assert.equal(state.mode, 'study', 'Mode-only sessions survive switching before Pi first writes a file');
  assert.equal(state.context.current, '03-Network/Network.md');
  await app.close(); await launch();
  state = (await call('state')).data;
  assert.equal(state.mode, 'study', 'Mode-only session survives process restart');
  assert.equal(state.context.current, '03-Network/Network.md');
  id = state.sessionId;
  assert.equal((await call('prompt', { sessionId: 'wrong', message: 'hold' })).status, 409);
  assert.equal((await call('prompt', { sessionId: id, message: 'hold' })).status, 200);
  state = await until(s => s.busy && s.sources.length === 2);
  assert.ok(state.messages.some(m => m.text.includes('\u2028')), 'RPC retains Unicode line separators');
  assert.equal(state.messages.filter(m => m.role === 'assistant').at(-1).text, '段落\u2028仍在同一則訊息\u2029。', 'An advanced message_start partial must not duplicate the first text delta');
  assert.equal((await call('mode', { sessionId: id, mode: 'research' })).status, 409, 'Busy mode change cannot be silently queued');
  assert.equal((await call('sessions', {})).status, 200, 'A running conversation must not block creating another conversation');
  assert.equal((await call('open', { id })).data.busy, true, 'Returning to the original conversation preserves its running state');
  const source = (await call(`sources/${state.sources[0].id}`)).data;
  assert.equal(source.content, '9: 原始證據\n10: 下一行');
  assert.equal((await call('sources/../../etc/passwd')).status, 404);
  events = new AbortController();
  const sse = await fetch(`${base}/api/events`, { signal: events.signal });
  assert.equal(sse.headers.get('content-type'), 'text/event-stream');
  const firstChunk = new TextDecoder().decode((await sse.body.getReader().read()).value);
  assert.ok(firstChunk.includes('event: snapshot'));
  assert.ok(firstChunk.includes('段落'));
  events.abort(); events = null;
  const stop = await call('stop', { sessionId: id });
  assert.equal(stop.status, 200); assert.equal(stop.data.restored, '未送出的訊息');
  state = await until(s => !s.busy);
  const log = (await readFile(join(root, 'rpc.log'), 'utf8')).trim().split('\n').map(JSON.parse);
  const stopIndex = log.findIndex(e => e.type === 'clear_queue'); assert.equal(log[stopIndex + 1].type, 'abort');
  assert.equal((await call('mode', { sessionId: id, mode: 'research' })).status, 200);
  const pendingPrompt = call('prompt', { sessionId: id, message: '/confirm' });
  await until(s => s.dialogs.length === 1);
  assert.equal((await call('ui', { sessionId: id, id: 'made-up', confirmed: true })).status, 409);
  assert.equal((await call('ui', { sessionId: id, id: 'dialog-1', cancelled: true })).status, 200, 'Dialogs can reply while prompt is pending');
  assert.equal((await pendingPrompt).status, 200);
  await until(s => !s.busy && !s.dialogs.length);
  await app.close(); await launch();
  state = (await call('state')).data;
  assert.equal(state.mode, 'research');
  assert.ok(state.messages.some(m => m.text.includes('完成')));
  assert.equal(state.sources.length, 1, 'Reload rebuilds only actual persisted evidence');
  console.log('Web RPC, sessions, streaming, dialogs, stop, and origin / Tailscale security checks passed');
} finally { events?.abort(); await app?.close(); await rm(root, { recursive: true, force: true }); }
